# Generated by Django 2.2.5 on 2020-01-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajas_teoricas', models.IntegerField(default=1, verbose_name='cajas_teoricas')),
                ('cajas_practicas', models.IntegerField(default=1, verbose_name='cajas_practicas')),
                ('imagen_sin_analizar', models.CharField(max_length=50, verbose_name='imagen_sin_analizar')),
                ('imagen_analizada', models.CharField(max_length=50, verbose_name='imagen_sin_analizar')),
                ('porcentaje', models.FloatField(default=1, verbose_name='porcentaje')),
            ],
            options={
                'verbose_name_plural': 'Historico_Imagenes',
                'db_table': 'Historico_Imagenes',
                'ordering': ['-id'],
            },
        ),
    ]
