# Generated by Django 2.2.5 on 2020-01-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_imagenes',
            name='imagen_sin_analizar',
            field=models.CharField(max_length=100, verbose_name='imagen_sin_analizar'),
        ),
    ]
