# Generated by Django 2.2.5 on 2020-01-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200123_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_imagenes',
            name='imagen_analizada',
            field=models.CharField(max_length=100, verbose_name='imagen_sin_analizar'),
        ),
    ]
