# Generated by Django 2.2.5 on 2020-02-23 03:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200126_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic_Vehicles_detected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, verbose_name='device_id')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('image', models.CharField(max_length=100, verbose_name='image')),
                ('vehicles_detected', models.IntegerField(verbose_name='')),
                ('awsRekognition_response', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='awsRekognition_response')),
            ],
            options={
                'verbose_name_plural': 'Historic_Vehicles_detected',
                'db_table': 'Historic_Vehicles_detected',
                'ordering': ['-id'],
            },
        ),
    ]
